language: python
services:
- postgresql
python:
- 3.5
before_install:
- openssl aes-256-cbc -K $encrypted_c3450097c79a_key -iv $encrypted_c3450097c79a_iv
  -in deploy_rsa.enc -out deploy_rsa -d
install:
- pip install -r requirements.txt
before_script:
- psql -c 'create database travis;' -U postgres
- autoflake --in-place --recursive --imports=django .
- pyflakes .
- echo -e "Host web518.webfaction.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
- python manage.py test home.tests
- coverage run --source=home manage.py test home.tests
after_success:
- coveralls
- chmod a+x ./after_success_script.sh
- ./after_success_script.sh
